name = "JeffClient"
uuid = "99eee0ee-b0c7-48fb-9455-442e76ba5e88"
version = "0.1.0"
authors = ["Satoshi Terasaki <terasakisatoshi.math@gmail.com>"]

[workspace]
projects = ["test", "tools", "docs"]

[deps]
Downloads = "f43a241f-c20a-4ad4-852c-f6b1247861c6"
JSON = "682c06a0-de6a-54ab-a142-c8b1cf79cde6"
LinearAlgebra = "37e2e46d-f89d-539d-b4ee-838fcccc9c8e"
ONNXRunTime = "e034b28e-924e-41b2-b98f-d2bbeb830c6a"
Scratch = "6c6a2e73-6563-6170-7368-637461726353"

[compat]
Octavian = "0.3.29"
SIMD = "3.7"
AppleAccelerate = "=0.7.0"
Downloads = "1.7.0"
JSON = "1.10.0"
LinearAlgebra = "1.13.0"
Metal = "=1.11.1"
ONNXRunTime = "1.3.4"
Scratch = "1.3.0"
julia = "1.13"

[weakdeps]
Octavian = "6fd5a793-0b7e-452c-907f-f8bfe9c57db4"
SIMD = "fdea26ae-647d-5447-a871-4b548cad5224"
AppleAccelerate = "13e28ba4-7ad8-5781-acae-3021b1ed3924"
Metal = "dde4c033-4e86-420c-a63e-0dd931031962"

[extensions]
JeffClientOctavianExt = "Octavian"
JeffClientSIMDExt = "SIMD"
JeffClientAppleAccelerateExt = "AppleAccelerate"
JeffClientMetalExt = "Metal"
